package org.centauron.ant.doclet;

import java.util.Date;

/**
 * Antdoc doclet
 *
 * Copyright: Copyright (c) 2002, Toni Thomsson, All rights reserved.
 * @author centauron
 */
public interface Constants
{
    public static final String BRANDING = "Generated by antdoc 0.7 from centauron at " + new Date();

    public static final String TAG_NODOC = "@ant.nodoc";
    public static final String TAG_TASKNAME = "@ant.taskname";
    public static final String TAG_OPTIONAL = "@ant.optional";
    public static final String TAG_DESCRIPTION = "@ant.description";
	public static final String TAG_DEPRECATED = "@ant.deprecated";
	public static final String TAG_EXAMPLE = "@ant.example";
	public static final String TAG_EXAMPLE_CODE = "@ant.example.code";
	public static final String TAG_EXAMPLE_DESCRIPTION = "@ant.example.description";
	public static final String TAG_NESTEDPARAMETER_NAME = "@ant.nested.name";
	public static final String TAG_NESTEDPARAMETER_DESCRIPTION = "@ant.nested.description";
	
	public static final String STANDARDTAG_CODE="@code";
	public static final String STANDARDTAG_LITERAL="@literal";
	public static final String STANDARDTAG_LINK="@link";
	
}